services: 
  ui-dev:
    build:
      context: .
      target: dev
    restart: unless-stopped
    environment:
      - PUBLIC_API=${PUBLIC_API}
      - API_GOOGLE_MAPS=${API_GOOGLE_MAPS}
      - HOST=0.0.0.0

    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      # - .node_modules:/usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"
    networks:
      - pinegrove-network

networks:
  pinegrove-network:
    external: true
    driver: bridge