services: 
  ui-dev:
    build:
      context: .
      target: dev
    restart: unless-stopped
    environment:
      - PUBLIC_API=${PUBLIC_API}
      - API_GOOGLE_MAPS=${API_GOOGLE_MAPS}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      # - .node_modules:/usr/src/app/node_modules
    ports:
      - 1234:3000

networks:
  follow-network:
    driver: bridge