services: 
  ui-dev:
    build:
      context: .
      target: dev
    restart: always
    environment:
      - PUBLIC_API=${PUBLIC_API}
      - API_GOOGLE_MAPS=${API_GOOGLE_MAPS}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      # - .node_modules:/usr/src/app/node_modules
    ports:
      - 1234:3000

  ui-prod:
    build:
      context: .
      target: production
    restart: always
    ports:
      - "80:80"
    environment:
      - PUBLIC_API=${PUBLIC_API}
      - API_GOOGLE_MAPS=${API_GOOGLE_MAPS}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  follow-network:
    driver: bridge